# Generated by Django 3.0.6 on 2020-06-09 12:26

import bocus.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='8esjs10a', max_length=20)),
                ('path', models.FilePathField(allow_folders=True, path=bocus.models.images_path)),
            ],
        ),
    ]
